package com.zyxist.example.dagger.framework.core.impl;

import com.zyxist.example.dagger.framework.core.api.CoreService;
import com.zyxist.example.dagger.framework.core.api.SecondExtensionPoint;
import java.util.Objects;
import javax.inject.Inject;

public class CoreServiceImpl implements CoreService {
	private final SecondExtensionPoint extension;
	
	@Inject
	public CoreServiceImpl(SecondExtensionPoint ext) {
		this.extension = Objects.requireNonNull(ext);
	}
	
	@Override
	public int getRandomNumber() {
		// generated by throwing a dice.
		return 4;
	}
	
	public String doSomethingInteresting() {
		return "foo " + extension.doSomething();
	}
}
